### ISSUE TITLE
pending cycle time.

### ISSUE THREAD

**Issue by coranos** [dev-ptera/thebananostand#6]
if you have a lot of pending transactions that they wont all go through properly. It took 3 attempts at receiving incoming for them all to properly go through. Most went through okay but some just basically got skipped until the second or third attempt of receiving for them to go through and to even get the notification on the ledger. I had 23 pending as i have not checked in on it for awhile.

This may be because the code only receives one block at a time, and it may need to be coded to check for more pending blocks

**Comment by dev-ptera** [comment]
I'm thinking this might just be a limitation of ledger devices; each tx will have to manually verified one at a time, so it makes sense to handle the receives for ledger individually.   I'll try to recreate the issue locally because I'm not sure why the amount of transactions would cause an issue.   

Maybe we could bulk-receive for the local seed/password managed accounts.

**Comment by dev-ptera** [comment]
I've updated the client to iterate through the currently-known list of receivable transactions.  Ledger devices & secret-using wallets that `auto-receive` enabled will now automatically receive incoming transactions.  Ledger devices without `auto-receive` enabled will still have to manually verify transactions on their ledger.
